import type { Metadata } from 'next'
import { Playfair_Display, DM_Sans } from 'next/font/google'
import './globals.css'

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-display',
  display: 'swap',
})

const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL('https://www.hemingwayengine.com'),
  title: {
    default: 'Hemingway Engine — AI Video Ads for DTC Brands',
    template: '%s | Hemingway Engine',
  },
  description:
    'Describe your product and get a finished video ad, UGC-style or cinematic, scripted and generated by AI for ecommerce and DTC brands.',
  openGraph: {
    title: 'Hemingway Engine — AI Video Ads for DTC Brands',
    description:
      'Describe your product and get a finished video ad, UGC-style or cinematic, scripted and generated by AI for ecommerce and DTC brands.',
    url: '/',
    siteName: 'Hemingway Engine',
    type: 'website',
  },
  twitter: {
    card: 'summary',
    title: 'Hemingway Engine — AI Video Ads for DTC Brands',
    description:
      'Describe your product and get a finished video ad, UGC-style or cinematic, scripted and generated by AI for ecommerce and DTC brands.',
  },
  alternates: {
    canonical: '/',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${playfair.variable} ${dmSans.variable}`}>
      <body className="min-h-screen bg-[#F7F5F2] font-sans text-ink antialiased">
        {children}
      </body>
    </html>
  )
}
